databases:
  - name: sparki-db
    databaseName: sparkidb
    user: sparki

services:
  - type: web
    name: sparki-backend
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: sparki-db
          property: connectionString
    healthCheckPath: /health
